services:
  db:
    image: postgres:14
    container_name: paypal_pg
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: paypal_test
    ports:
      - 5432:5432
  backend:
    build: .
    container_name: paypal_app
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - 8000:8000